# Generated by Django 5.0.1 on 2024-01-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeproduct',
            options={'verbose_name': 'Рецепт - продукт', 'verbose_name_plural': 'Рецепты - продукты'},
        ),
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='weight_in_grams',
            new_name='weight',
        ),
    ]
