# Generated by Django 5.0.1 on 2024-01-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_recipeproduct_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='weight',
            new_name='weight_in_grams',
        ),
    ]
